require 'human_error/errors/request_error'
require 'human_error/errors/authentication_error'
require 'human_error/errors/authentication_errors/invalid_token_error'
require 'human_error/errors/authentication_errors/invalid_username_or_password_error'
require 'human_error/errors/crud_error'
require 'human_error/errors/crud_errors/resource_not_found_error'
require 'human_error/errors/crud_errors/resource_persistence_error'
