language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
script: bundle exec rspec spec
env:
  global:
    secure: JLY1ZD0y8PjuHq5u3AFBJFLwP8dvM0XM40tXSGjTeGwUhr9ZJDC2sR3iHq32VssxOHxtqTYfRlxDU91hF8XK60MdTT0euMEhjfT1kx3t3Gj/Q0jo6xDcaZCVObANu+nhtB59rUR7ddMIet6Zm7w5tgTskN+lem3OhDYtzgY6CLc=
notifications:
  slack:
    rooms:
    - thekompanee:p46x27zMG89XW66DgGuutoaW#open-source
